apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo1
  namespace: default
spec:
  interval: 5m
  path: "./demo1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo1
