apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: demo1:1.0.2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: demo1
