apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo1
  labels:
    app: demo1
spec:
  type: ClusterIP
  selector:
    app: demo1
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
